artifacts_config:
  artifacts_dir: artifacts


data_ingestion:
  dataset_url: 'Table_1.csv'
  dataset_dir: dataset
  ingested_dir: ingested_data
  raw_data_dir: raw_data
  dataset: Table_1.csv 

data_validation_config:
  clean_data_dir: clean_data
  serialized_obj_dir: serialized_obj
  marketing_compaign_csv_file: marketing_compaign.csv

data_transformation:
  transformed_data_dir: transformed_data
  # preprocessod_obj: artifacts/transformation/pre_pro.pkl


model_training:
  trained_model_dir: trained_model
  trained_model_name: model.pkl