
columns:
  table_id: int64
  name: object
  phone_number: int64
  location: object
  emp_group: object
  function: object
  gender: object
  tenure: float64
  tenure_grp: object
  experience_yymm: float64
  marital_status: object
  age_in_yy: float64
  hiring_source: object
  promoted_non_promoted: object
  job_role_match: object
  stay_left: object

categorical_columns:
  - name
  - location
  - emp_group
  - function
  - gender
  - tenure_grp
  - marital_status
  - hiring_source
  - promoted_non_promoted
  - job_role_match
  

numerical_columns:
  - table_id
  - phone_number
  - tenure
  - experience_yymm
  - age_in_yy


target_column: stay_left